name: appcues_flutter
description: Plugin package to bridge the native Appcues SDKs in a Flutter application.
version: 5.0.1
homepage: https://www.appcues.com
repository: https://github.com/appcues/appcues-flutter-plugin
environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.appcues.flutter
        pluginClass: AppcuesFlutterPlugin
      ios:
        pluginClass: AppcuesFlutterPlugin
